[project]
name = "menu-optimizer"
version = "0.1.0"
description = "Menu Optimizer MILP"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pulp>=3.3.0",
]
authors = [
    { name = "James Ott" }
]
